/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestPasswordResetRouteImport } from './routes/request-password-reset'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountDeletedRouteImport } from './routes/account-deleted'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTravelsIndexRouteImport } from './routes/_authenticated/travels/index'
import { Route as AuthenticatedTravelsNewRouteImport } from './routes/_authenticated/travels/new'
import { Route as AuthenticatedTravelsJoinRouteImport } from './routes/_authenticated/travels/join'
import { Route as AuthenticatedTravelsTravelIdRouteImport } from './routes/_authenticated/travels/$travelId'
import { Route as AuthenticatedTravelsTravelIdIndexRouteImport } from './routes/_authenticated/travels/$travelId/index'
import { Route as AuthenticatedTravelsTravelIdUsersIndexRouteImport } from './routes/_authenticated/travels/$travelId/users/index'
import { Route as AuthenticatedTravelsTravelIdTransactionsIndexRouteImport } from './routes/_authenticated/travels/$travelId/transactions/index'
import { Route as AuthenticatedTravelsTravelIdExploreIndexRouteImport } from './routes/_authenticated/travels/$travelId/explore/index'
import { Route as AuthenticatedTravelsTravelIdCurrenciesIndexRouteImport } from './routes/_authenticated/travels/$travelId/currencies/index'
import { Route as AuthenticatedTravelsTravelIdBalancesIndexRouteImport } from './routes/_authenticated/travels/$travelId/balances/index'
import { Route as AuthenticatedTravelsTravelIdAnalyseIndexRouteImport } from './routes/_authenticated/travels/$travelId/analyse/index'
import { Route as AuthenticatedTravelsTravelIdPlacesPlaceIdRouteImport } from './routes/_authenticated/travels/$travelId/places/$placeId'
import { Route as AuthenticatedTravelsTravelIdBudgetsConfigureRouteImport } from './routes/_authenticated/travels/$travelId/budgets/configure'
import { Route as AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRouteImport } from './routes/_authenticated/travels/$travelId/categories/$categoryType/index'
import { Route as AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRouteImport } from './routes/_authenticated/travels/$travelId/categories/$categoryType/manage'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestPasswordResetRoute = RequestPasswordResetRouteImport.update({
  id: '/request-password-reset',
  path: '/request-password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletedRoute = AccountDeletedRouteImport.update({
  id: '/account-deleted',
  path: '/account-deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTravelsIndexRoute =
  AuthenticatedTravelsIndexRouteImport.update({
    id: '/travels/',
    path: '/travels/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelsNewRoute = AuthenticatedTravelsNewRouteImport.update({
  id: '/travels/new',
  path: '/travels/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTravelsJoinRoute =
  AuthenticatedTravelsJoinRouteImport.update({
    id: '/travels/join',
    path: '/travels/join',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelsTravelIdRoute =
  AuthenticatedTravelsTravelIdRouteImport.update({
    id: '/travels/$travelId',
    path: '/travels/$travelId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelsTravelIdIndexRoute =
  AuthenticatedTravelsTravelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdUsersIndexRoute =
  AuthenticatedTravelsTravelIdUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdTransactionsIndexRoute =
  AuthenticatedTravelsTravelIdTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdExploreIndexRoute =
  AuthenticatedTravelsTravelIdExploreIndexRouteImport.update({
    id: '/explore/',
    path: '/explore/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdCurrenciesIndexRoute =
  AuthenticatedTravelsTravelIdCurrenciesIndexRouteImport.update({
    id: '/currencies/',
    path: '/currencies/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdBalancesIndexRoute =
  AuthenticatedTravelsTravelIdBalancesIndexRouteImport.update({
    id: '/balances/',
    path: '/balances/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdAnalyseIndexRoute =
  AuthenticatedTravelsTravelIdAnalyseIndexRouteImport.update({
    id: '/analyse/',
    path: '/analyse/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdPlacesPlaceIdRoute =
  AuthenticatedTravelsTravelIdPlacesPlaceIdRouteImport.update({
    id: '/places/$placeId',
    path: '/places/$placeId',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdBudgetsConfigureRoute =
  AuthenticatedTravelsTravelIdBudgetsConfigureRouteImport.update({
    id: '/budgets/configure',
    path: '/budgets/configure',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRoute =
  AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRouteImport.update({
    id: '/categories/$categoryType/',
    path: '/categories/$categoryType/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRoute =
  AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRouteImport.update({
    id: '/categories/$categoryType/manage',
    path: '/categories/$categoryType/manage',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/login': typeof LoginRoute
  '/request-password-reset': typeof RequestPasswordResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteWithChildren
  '/travels/join': typeof AuthenticatedTravelsJoinRoute
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/travels': typeof AuthenticatedTravelsIndexRoute
  '/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
  '/travels/$travelId/budgets/configure': typeof AuthenticatedTravelsTravelIdBudgetsConfigureRoute
  '/travels/$travelId/places/$placeId': typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRoute
  '/travels/$travelId/analyse': typeof AuthenticatedTravelsTravelIdAnalyseIndexRoute
  '/travels/$travelId/balances': typeof AuthenticatedTravelsTravelIdBalancesIndexRoute
  '/travels/$travelId/currencies': typeof AuthenticatedTravelsTravelIdCurrenciesIndexRoute
  '/travels/$travelId/explore': typeof AuthenticatedTravelsTravelIdExploreIndexRoute
  '/travels/$travelId/transactions': typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
  '/travels/$travelId/users': typeof AuthenticatedTravelsTravelIdUsersIndexRoute
  '/travels/$travelId/categories/$categoryType/manage': typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRoute
  '/travels/$travelId/categories/$categoryType': typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/login': typeof LoginRoute
  '/request-password-reset': typeof RequestPasswordResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/travels/join': typeof AuthenticatedTravelsJoinRoute
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/travels': typeof AuthenticatedTravelsIndexRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdIndexRoute
  '/travels/$travelId/budgets/configure': typeof AuthenticatedTravelsTravelIdBudgetsConfigureRoute
  '/travels/$travelId/places/$placeId': typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRoute
  '/travels/$travelId/analyse': typeof AuthenticatedTravelsTravelIdAnalyseIndexRoute
  '/travels/$travelId/balances': typeof AuthenticatedTravelsTravelIdBalancesIndexRoute
  '/travels/$travelId/currencies': typeof AuthenticatedTravelsTravelIdCurrenciesIndexRoute
  '/travels/$travelId/explore': typeof AuthenticatedTravelsTravelIdExploreIndexRoute
  '/travels/$travelId/transactions': typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
  '/travels/$travelId/users': typeof AuthenticatedTravelsTravelIdUsersIndexRoute
  '/travels/$travelId/categories/$categoryType/manage': typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRoute
  '/travels/$travelId/categories/$categoryType': typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/account-deleted': typeof AccountDeletedRoute
  '/login': typeof LoginRoute
  '/request-password-reset': typeof RequestPasswordResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteWithChildren
  '/_authenticated/travels/join': typeof AuthenticatedTravelsJoinRoute
  '/_authenticated/travels/new': typeof AuthenticatedTravelsNewRoute
  '/_authenticated/travels/': typeof AuthenticatedTravelsIndexRoute
  '/_authenticated/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
  '/_authenticated/travels/$travelId/budgets/configure': typeof AuthenticatedTravelsTravelIdBudgetsConfigureRoute
  '/_authenticated/travels/$travelId/places/$placeId': typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRoute
  '/_authenticated/travels/$travelId/analyse/': typeof AuthenticatedTravelsTravelIdAnalyseIndexRoute
  '/_authenticated/travels/$travelId/balances/': typeof AuthenticatedTravelsTravelIdBalancesIndexRoute
  '/_authenticated/travels/$travelId/currencies/': typeof AuthenticatedTravelsTravelIdCurrenciesIndexRoute
  '/_authenticated/travels/$travelId/explore/': typeof AuthenticatedTravelsTravelIdExploreIndexRoute
  '/_authenticated/travels/$travelId/transactions/': typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
  '/_authenticated/travels/$travelId/users/': typeof AuthenticatedTravelsTravelIdUsersIndexRoute
  '/_authenticated/travels/$travelId/categories/$categoryType/manage': typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRoute
  '/_authenticated/travels/$travelId/categories/$categoryType/': typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deleted'
    | '/login'
    | '/request-password-reset'
    | '/reset-password'
    | '/signup'
    | '/profile'
    | '/travels/$travelId'
    | '/travels/join'
    | '/travels/new'
    | '/travels'
    | '/travels/$travelId/'
    | '/travels/$travelId/budgets/configure'
    | '/travels/$travelId/places/$placeId'
    | '/travels/$travelId/analyse'
    | '/travels/$travelId/balances'
    | '/travels/$travelId/currencies'
    | '/travels/$travelId/explore'
    | '/travels/$travelId/transactions'
    | '/travels/$travelId/users'
    | '/travels/$travelId/categories/$categoryType/manage'
    | '/travels/$travelId/categories/$categoryType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deleted'
    | '/login'
    | '/request-password-reset'
    | '/reset-password'
    | '/signup'
    | '/profile'
    | '/travels/join'
    | '/travels/new'
    | '/travels'
    | '/travels/$travelId'
    | '/travels/$travelId/budgets/configure'
    | '/travels/$travelId/places/$placeId'
    | '/travels/$travelId/analyse'
    | '/travels/$travelId/balances'
    | '/travels/$travelId/currencies'
    | '/travels/$travelId/explore'
    | '/travels/$travelId/transactions'
    | '/travels/$travelId/users'
    | '/travels/$travelId/categories/$categoryType/manage'
    | '/travels/$travelId/categories/$categoryType'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account-deleted'
    | '/login'
    | '/request-password-reset'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/profile'
    | '/_authenticated/travels/$travelId'
    | '/_authenticated/travels/join'
    | '/_authenticated/travels/new'
    | '/_authenticated/travels/'
    | '/_authenticated/travels/$travelId/'
    | '/_authenticated/travels/$travelId/budgets/configure'
    | '/_authenticated/travels/$travelId/places/$placeId'
    | '/_authenticated/travels/$travelId/analyse/'
    | '/_authenticated/travels/$travelId/balances/'
    | '/_authenticated/travels/$travelId/currencies/'
    | '/_authenticated/travels/$travelId/explore/'
    | '/_authenticated/travels/$travelId/transactions/'
    | '/_authenticated/travels/$travelId/users/'
    | '/_authenticated/travels/$travelId/categories/$categoryType/manage'
    | '/_authenticated/travels/$travelId/categories/$categoryType/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccountDeletedRoute: typeof AccountDeletedRoute
  LoginRoute: typeof LoginRoute
  RequestPasswordResetRoute: typeof RequestPasswordResetRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-password-reset': {
      id: '/request-password-reset'
      path: '/request-password-reset'
      fullPath: '/request-password-reset'
      preLoaderRoute: typeof RequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deleted': {
      id: '/account-deleted'
      path: '/account-deleted'
      fullPath: '/account-deleted'
      preLoaderRoute: typeof AccountDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/': {
      id: '/_authenticated/travels/'
      path: '/travels'
      fullPath: '/travels'
      preLoaderRoute: typeof AuthenticatedTravelsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/new': {
      id: '/_authenticated/travels/new'
      path: '/travels/new'
      fullPath: '/travels/new'
      preLoaderRoute: typeof AuthenticatedTravelsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/join': {
      id: '/_authenticated/travels/join'
      path: '/travels/join'
      fullPath: '/travels/join'
      preLoaderRoute: typeof AuthenticatedTravelsJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId': {
      id: '/_authenticated/travels/$travelId'
      path: '/travels/$travelId'
      fullPath: '/travels/$travelId'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId/': {
      id: '/_authenticated/travels/$travelId/'
      path: '/'
      fullPath: '/travels/$travelId/'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/users/': {
      id: '/_authenticated/travels/$travelId/users/'
      path: '/users'
      fullPath: '/travels/$travelId/users'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdUsersIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/transactions/': {
      id: '/_authenticated/travels/$travelId/transactions/'
      path: '/transactions'
      fullPath: '/travels/$travelId/transactions'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/explore/': {
      id: '/_authenticated/travels/$travelId/explore/'
      path: '/explore'
      fullPath: '/travels/$travelId/explore'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdExploreIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/currencies/': {
      id: '/_authenticated/travels/$travelId/currencies/'
      path: '/currencies'
      fullPath: '/travels/$travelId/currencies'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdCurrenciesIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/balances/': {
      id: '/_authenticated/travels/$travelId/balances/'
      path: '/balances'
      fullPath: '/travels/$travelId/balances'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdBalancesIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/analyse/': {
      id: '/_authenticated/travels/$travelId/analyse/'
      path: '/analyse'
      fullPath: '/travels/$travelId/analyse'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdAnalyseIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/places/$placeId': {
      id: '/_authenticated/travels/$travelId/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/travels/$travelId/places/$placeId'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/budgets/configure': {
      id: '/_authenticated/travels/$travelId/budgets/configure'
      path: '/budgets/configure'
      fullPath: '/travels/$travelId/budgets/configure'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdBudgetsConfigureRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/categories/$categoryType/': {
      id: '/_authenticated/travels/$travelId/categories/$categoryType/'
      path: '/categories/$categoryType'
      fullPath: '/travels/$travelId/categories/$categoryType'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/categories/$categoryType/manage': {
      id: '/_authenticated/travels/$travelId/categories/$categoryType/manage'
      path: '/categories/$categoryType/manage'
      fullPath: '/travels/$travelId/categories/$categoryType/manage'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
  }
}

interface AuthenticatedTravelsTravelIdRouteChildren {
  AuthenticatedTravelsTravelIdIndexRoute: typeof AuthenticatedTravelsTravelIdIndexRoute
  AuthenticatedTravelsTravelIdBudgetsConfigureRoute: typeof AuthenticatedTravelsTravelIdBudgetsConfigureRoute
  AuthenticatedTravelsTravelIdPlacesPlaceIdRoute: typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRoute
  AuthenticatedTravelsTravelIdAnalyseIndexRoute: typeof AuthenticatedTravelsTravelIdAnalyseIndexRoute
  AuthenticatedTravelsTravelIdBalancesIndexRoute: typeof AuthenticatedTravelsTravelIdBalancesIndexRoute
  AuthenticatedTravelsTravelIdCurrenciesIndexRoute: typeof AuthenticatedTravelsTravelIdCurrenciesIndexRoute
  AuthenticatedTravelsTravelIdExploreIndexRoute: typeof AuthenticatedTravelsTravelIdExploreIndexRoute
  AuthenticatedTravelsTravelIdTransactionsIndexRoute: typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
  AuthenticatedTravelsTravelIdUsersIndexRoute: typeof AuthenticatedTravelsTravelIdUsersIndexRoute
  AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRoute: typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRoute
  AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRoute: typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRoute
}

const AuthenticatedTravelsTravelIdRouteChildren: AuthenticatedTravelsTravelIdRouteChildren =
  {
    AuthenticatedTravelsTravelIdIndexRoute:
      AuthenticatedTravelsTravelIdIndexRoute,
    AuthenticatedTravelsTravelIdBudgetsConfigureRoute:
      AuthenticatedTravelsTravelIdBudgetsConfigureRoute,
    AuthenticatedTravelsTravelIdPlacesPlaceIdRoute:
      AuthenticatedTravelsTravelIdPlacesPlaceIdRoute,
    AuthenticatedTravelsTravelIdAnalyseIndexRoute:
      AuthenticatedTravelsTravelIdAnalyseIndexRoute,
    AuthenticatedTravelsTravelIdBalancesIndexRoute:
      AuthenticatedTravelsTravelIdBalancesIndexRoute,
    AuthenticatedTravelsTravelIdCurrenciesIndexRoute:
      AuthenticatedTravelsTravelIdCurrenciesIndexRoute,
    AuthenticatedTravelsTravelIdExploreIndexRoute:
      AuthenticatedTravelsTravelIdExploreIndexRoute,
    AuthenticatedTravelsTravelIdTransactionsIndexRoute:
      AuthenticatedTravelsTravelIdTransactionsIndexRoute,
    AuthenticatedTravelsTravelIdUsersIndexRoute:
      AuthenticatedTravelsTravelIdUsersIndexRoute,
    AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRoute:
      AuthenticatedTravelsTravelIdCategoriesCategoryTypeManageRoute,
    AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRoute:
      AuthenticatedTravelsTravelIdCategoriesCategoryTypeIndexRoute,
  }

const AuthenticatedTravelsTravelIdRouteWithChildren =
  AuthenticatedTravelsTravelIdRoute._addFileChildren(
    AuthenticatedTravelsTravelIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTravelsTravelIdRoute: typeof AuthenticatedTravelsTravelIdRouteWithChildren
  AuthenticatedTravelsJoinRoute: typeof AuthenticatedTravelsJoinRoute
  AuthenticatedTravelsNewRoute: typeof AuthenticatedTravelsNewRoute
  AuthenticatedTravelsIndexRoute: typeof AuthenticatedTravelsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTravelsTravelIdRoute:
    AuthenticatedTravelsTravelIdRouteWithChildren,
  AuthenticatedTravelsJoinRoute: AuthenticatedTravelsJoinRoute,
  AuthenticatedTravelsNewRoute: AuthenticatedTravelsNewRoute,
  AuthenticatedTravelsIndexRoute: AuthenticatedTravelsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccountDeletedRoute: AccountDeletedRoute,
  LoginRoute: LoginRoute,
  RequestPasswordResetRoute: RequestPasswordResetRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
