/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTravelsNewRouteImport } from './routes/_authenticated/travels/new'
import { Route as AuthenticatedTravelsTravelIdRouteImport } from './routes/_authenticated/travels/$travelId'
import { Route as AuthenticatedTravelsTravelIdIndexRouteImport } from './routes/_authenticated/travels/$travelId/index'
import { Route as AuthenticatedTravelsTravelIdUsersIndexRouteImport } from './routes/_authenticated/travels/$travelId/users/index'
import { Route as AuthenticatedTravelsTravelIdTransactionsIndexRouteImport } from './routes/_authenticated/travels/$travelId/transactions/index'
import { Route as AuthenticatedTravelsTravelIdPlacesIndexRouteImport } from './routes/_authenticated/travels/$travelId/places/index'
import { Route as AuthenticatedTravelsTravelIdCategoriesIndexRouteImport } from './routes/_authenticated/travels/$travelId/categories/index'
import { Route as AuthenticatedTravelsTravelIdBudgetsIndexRouteImport } from './routes/_authenticated/travels/$travelId/budgets/index'
import { Route as AuthenticatedTravelsTravelIdUsersMeRouteImport } from './routes/_authenticated/travels/$travelId/users/me'
import { Route as AuthenticatedTravelsTravelIdPlacesPlaceIdRouteImport } from './routes/_authenticated/travels/$travelId/places/$placeId'
import { Route as AuthenticatedTravelsTravelIdCategoriesCategoryTypeRouteImport } from './routes/_authenticated/travels/$travelId/categories/$categoryType'
import { Route as AuthenticatedTravelsTravelIdBudgetsConfigureRouteImport } from './routes/_authenticated/travels/$travelId/budgets/configure'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTravelsNewRoute = AuthenticatedTravelsNewRouteImport.update({
  id: '/travels/new',
  path: '/travels/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTravelsTravelIdRoute =
  AuthenticatedTravelsTravelIdRouteImport.update({
    id: '/travels/$travelId',
    path: '/travels/$travelId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelsTravelIdIndexRoute =
  AuthenticatedTravelsTravelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdUsersIndexRoute =
  AuthenticatedTravelsTravelIdUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdTransactionsIndexRoute =
  AuthenticatedTravelsTravelIdTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdPlacesIndexRoute =
  AuthenticatedTravelsTravelIdPlacesIndexRouteImport.update({
    id: '/places/',
    path: '/places/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdCategoriesIndexRoute =
  AuthenticatedTravelsTravelIdCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdBudgetsIndexRoute =
  AuthenticatedTravelsTravelIdBudgetsIndexRouteImport.update({
    id: '/budgets/',
    path: '/budgets/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdUsersMeRoute =
  AuthenticatedTravelsTravelIdUsersMeRouteImport.update({
    id: '/users/me',
    path: '/users/me',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdPlacesPlaceIdRoute =
  AuthenticatedTravelsTravelIdPlacesPlaceIdRouteImport.update({
    id: '/places/$placeId',
    path: '/places/$placeId',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdCategoriesCategoryTypeRoute =
  AuthenticatedTravelsTravelIdCategoriesCategoryTypeRouteImport.update({
    id: '/categories/$categoryType',
    path: '/categories/$categoryType',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdBudgetsConfigureRoute =
  AuthenticatedTravelsTravelIdBudgetsConfigureRouteImport.update({
    id: '/budgets/configure',
    path: '/budgets/configure',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteWithChildren
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
  '/travels/$travelId/budgets/configure': typeof AuthenticatedTravelsTravelIdBudgetsConfigureRoute
  '/travels/$travelId/categories/$categoryType': typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeRoute
  '/travels/$travelId/places/$placeId': typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRoute
  '/travels/$travelId/users/me': typeof AuthenticatedTravelsTravelIdUsersMeRoute
  '/travels/$travelId/budgets': typeof AuthenticatedTravelsTravelIdBudgetsIndexRoute
  '/travels/$travelId/categories': typeof AuthenticatedTravelsTravelIdCategoriesIndexRoute
  '/travels/$travelId/places': typeof AuthenticatedTravelsTravelIdPlacesIndexRoute
  '/travels/$travelId/transactions': typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
  '/travels/$travelId/users': typeof AuthenticatedTravelsTravelIdUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdIndexRoute
  '/travels/$travelId/budgets/configure': typeof AuthenticatedTravelsTravelIdBudgetsConfigureRoute
  '/travels/$travelId/categories/$categoryType': typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeRoute
  '/travels/$travelId/places/$placeId': typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRoute
  '/travels/$travelId/users/me': typeof AuthenticatedTravelsTravelIdUsersMeRoute
  '/travels/$travelId/budgets': typeof AuthenticatedTravelsTravelIdBudgetsIndexRoute
  '/travels/$travelId/categories': typeof AuthenticatedTravelsTravelIdCategoriesIndexRoute
  '/travels/$travelId/places': typeof AuthenticatedTravelsTravelIdPlacesIndexRoute
  '/travels/$travelId/transactions': typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
  '/travels/$travelId/users': typeof AuthenticatedTravelsTravelIdUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteWithChildren
  '/_authenticated/travels/new': typeof AuthenticatedTravelsNewRoute
  '/_authenticated/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
  '/_authenticated/travels/$travelId/budgets/configure': typeof AuthenticatedTravelsTravelIdBudgetsConfigureRoute
  '/_authenticated/travels/$travelId/categories/$categoryType': typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeRoute
  '/_authenticated/travels/$travelId/places/$placeId': typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRoute
  '/_authenticated/travels/$travelId/users/me': typeof AuthenticatedTravelsTravelIdUsersMeRoute
  '/_authenticated/travels/$travelId/budgets/': typeof AuthenticatedTravelsTravelIdBudgetsIndexRoute
  '/_authenticated/travels/$travelId/categories/': typeof AuthenticatedTravelsTravelIdCategoriesIndexRoute
  '/_authenticated/travels/$travelId/places/': typeof AuthenticatedTravelsTravelIdPlacesIndexRoute
  '/_authenticated/travels/$travelId/transactions/': typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
  '/_authenticated/travels/$travelId/users/': typeof AuthenticatedTravelsTravelIdUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/profile'
    | '/'
    | '/travels/$travelId'
    | '/travels/new'
    | '/travels/$travelId/'
    | '/travels/$travelId/budgets/configure'
    | '/travels/$travelId/categories/$categoryType'
    | '/travels/$travelId/places/$placeId'
    | '/travels/$travelId/users/me'
    | '/travels/$travelId/budgets'
    | '/travels/$travelId/categories'
    | '/travels/$travelId/places'
    | '/travels/$travelId/transactions'
    | '/travels/$travelId/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/profile'
    | '/'
    | '/travels/new'
    | '/travels/$travelId'
    | '/travels/$travelId/budgets/configure'
    | '/travels/$travelId/categories/$categoryType'
    | '/travels/$travelId/places/$placeId'
    | '/travels/$travelId/users/me'
    | '/travels/$travelId/budgets'
    | '/travels/$travelId/categories'
    | '/travels/$travelId/places'
    | '/travels/$travelId/transactions'
    | '/travels/$travelId/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/travels/$travelId'
    | '/_authenticated/travels/new'
    | '/_authenticated/travels/$travelId/'
    | '/_authenticated/travels/$travelId/budgets/configure'
    | '/_authenticated/travels/$travelId/categories/$categoryType'
    | '/_authenticated/travels/$travelId/places/$placeId'
    | '/_authenticated/travels/$travelId/users/me'
    | '/_authenticated/travels/$travelId/budgets/'
    | '/_authenticated/travels/$travelId/categories/'
    | '/_authenticated/travels/$travelId/places/'
    | '/_authenticated/travels/$travelId/transactions/'
    | '/_authenticated/travels/$travelId/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/new': {
      id: '/_authenticated/travels/new'
      path: '/travels/new'
      fullPath: '/travels/new'
      preLoaderRoute: typeof AuthenticatedTravelsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId': {
      id: '/_authenticated/travels/$travelId'
      path: '/travels/$travelId'
      fullPath: '/travels/$travelId'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId/': {
      id: '/_authenticated/travels/$travelId/'
      path: '/'
      fullPath: '/travels/$travelId/'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/users/': {
      id: '/_authenticated/travels/$travelId/users/'
      path: '/users'
      fullPath: '/travels/$travelId/users'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdUsersIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/transactions/': {
      id: '/_authenticated/travels/$travelId/transactions/'
      path: '/transactions'
      fullPath: '/travels/$travelId/transactions'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/places/': {
      id: '/_authenticated/travels/$travelId/places/'
      path: '/places'
      fullPath: '/travels/$travelId/places'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdPlacesIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/categories/': {
      id: '/_authenticated/travels/$travelId/categories/'
      path: '/categories'
      fullPath: '/travels/$travelId/categories'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/budgets/': {
      id: '/_authenticated/travels/$travelId/budgets/'
      path: '/budgets'
      fullPath: '/travels/$travelId/budgets'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdBudgetsIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/users/me': {
      id: '/_authenticated/travels/$travelId/users/me'
      path: '/users/me'
      fullPath: '/travels/$travelId/users/me'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdUsersMeRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/places/$placeId': {
      id: '/_authenticated/travels/$travelId/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/travels/$travelId/places/$placeId'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/categories/$categoryType': {
      id: '/_authenticated/travels/$travelId/categories/$categoryType'
      path: '/categories/$categoryType'
      fullPath: '/travels/$travelId/categories/$categoryType'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/budgets/configure': {
      id: '/_authenticated/travels/$travelId/budgets/configure'
      path: '/budgets/configure'
      fullPath: '/travels/$travelId/budgets/configure'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdBudgetsConfigureRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
  }
}

interface AuthenticatedTravelsTravelIdRouteChildren {
  AuthenticatedTravelsTravelIdIndexRoute: typeof AuthenticatedTravelsTravelIdIndexRoute
  AuthenticatedTravelsTravelIdBudgetsConfigureRoute: typeof AuthenticatedTravelsTravelIdBudgetsConfigureRoute
  AuthenticatedTravelsTravelIdCategoriesCategoryTypeRoute: typeof AuthenticatedTravelsTravelIdCategoriesCategoryTypeRoute
  AuthenticatedTravelsTravelIdPlacesPlaceIdRoute: typeof AuthenticatedTravelsTravelIdPlacesPlaceIdRoute
  AuthenticatedTravelsTravelIdUsersMeRoute: typeof AuthenticatedTravelsTravelIdUsersMeRoute
  AuthenticatedTravelsTravelIdBudgetsIndexRoute: typeof AuthenticatedTravelsTravelIdBudgetsIndexRoute
  AuthenticatedTravelsTravelIdCategoriesIndexRoute: typeof AuthenticatedTravelsTravelIdCategoriesIndexRoute
  AuthenticatedTravelsTravelIdPlacesIndexRoute: typeof AuthenticatedTravelsTravelIdPlacesIndexRoute
  AuthenticatedTravelsTravelIdTransactionsIndexRoute: typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
  AuthenticatedTravelsTravelIdUsersIndexRoute: typeof AuthenticatedTravelsTravelIdUsersIndexRoute
}

const AuthenticatedTravelsTravelIdRouteChildren: AuthenticatedTravelsTravelIdRouteChildren =
  {
    AuthenticatedTravelsTravelIdIndexRoute:
      AuthenticatedTravelsTravelIdIndexRoute,
    AuthenticatedTravelsTravelIdBudgetsConfigureRoute:
      AuthenticatedTravelsTravelIdBudgetsConfigureRoute,
    AuthenticatedTravelsTravelIdCategoriesCategoryTypeRoute:
      AuthenticatedTravelsTravelIdCategoriesCategoryTypeRoute,
    AuthenticatedTravelsTravelIdPlacesPlaceIdRoute:
      AuthenticatedTravelsTravelIdPlacesPlaceIdRoute,
    AuthenticatedTravelsTravelIdUsersMeRoute:
      AuthenticatedTravelsTravelIdUsersMeRoute,
    AuthenticatedTravelsTravelIdBudgetsIndexRoute:
      AuthenticatedTravelsTravelIdBudgetsIndexRoute,
    AuthenticatedTravelsTravelIdCategoriesIndexRoute:
      AuthenticatedTravelsTravelIdCategoriesIndexRoute,
    AuthenticatedTravelsTravelIdPlacesIndexRoute:
      AuthenticatedTravelsTravelIdPlacesIndexRoute,
    AuthenticatedTravelsTravelIdTransactionsIndexRoute:
      AuthenticatedTravelsTravelIdTransactionsIndexRoute,
    AuthenticatedTravelsTravelIdUsersIndexRoute:
      AuthenticatedTravelsTravelIdUsersIndexRoute,
  }

const AuthenticatedTravelsTravelIdRouteWithChildren =
  AuthenticatedTravelsTravelIdRoute._addFileChildren(
    AuthenticatedTravelsTravelIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTravelsTravelIdRoute: typeof AuthenticatedTravelsTravelIdRouteWithChildren
  AuthenticatedTravelsNewRoute: typeof AuthenticatedTravelsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTravelsTravelIdRoute:
    AuthenticatedTravelsTravelIdRouteWithChildren,
  AuthenticatedTravelsNewRoute: AuthenticatedTravelsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
