/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as AuthenticatedTravelsNewRouteImport } from './routes/_authenticated/travels/new'
import { Route as AuthenticatedTravelsTravelIdRouteImport } from './routes/_authenticated/travels/$travelId'
import { Route as AuthenticatedTravelsTravelIdIndexRouteImport } from './routes/_authenticated/travels/$travelId/index'
import { Route as AuthenticatedTravelsTravelIdTransactionsIndexRouteImport } from './routes/_authenticated/travels/$travelId/transactions/index'
import { Route as AuthenticatedTravelsTravelIdSettingsIndexRouteImport } from './routes/_authenticated/travels/$travelId/settings/index'
import { Route as AuthenticatedTravelsTravelIdSettingsUsersRouteImport } from './routes/_authenticated/travels/$travelId/settings/users'
import { Route as AuthenticatedTravelsTravelIdSettingsCategoriesRouteImport } from './routes/_authenticated/travels/$travelId/settings/categories'
import { Route as AuthenticatedTravelsTravelIdSettingsBudgetsRouteImport } from './routes/_authenticated/travels/$travelId/settings/budgets'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTravelsNewRoute = AuthenticatedTravelsNewRouteImport.update({
  id: '/travels/new',
  path: '/travels/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTravelsTravelIdRoute =
  AuthenticatedTravelsTravelIdRouteImport.update({
    id: '/travels/$travelId',
    path: '/travels/$travelId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTravelsTravelIdIndexRoute =
  AuthenticatedTravelsTravelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdTransactionsIndexRoute =
  AuthenticatedTravelsTravelIdTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdSettingsIndexRoute =
  AuthenticatedTravelsTravelIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdSettingsUsersRoute =
  AuthenticatedTravelsTravelIdSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdSettingsCategoriesRoute =
  AuthenticatedTravelsTravelIdSettingsCategoriesRouteImport.update({
    id: '/settings/categories',
    path: '/settings/categories',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)
const AuthenticatedTravelsTravelIdSettingsBudgetsRoute =
  AuthenticatedTravelsTravelIdSettingsBudgetsRouteImport.update({
    id: '/settings/budgets',
    path: '/settings/budgets',
    getParentRoute: () => AuthenticatedTravelsTravelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/auth': typeof ApiAuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteWithChildren
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
  '/travels/$travelId/settings/budgets': typeof AuthenticatedTravelsTravelIdSettingsBudgetsRoute
  '/travels/$travelId/settings/categories': typeof AuthenticatedTravelsTravelIdSettingsCategoriesRoute
  '/travels/$travelId/settings/users': typeof AuthenticatedTravelsTravelIdSettingsUsersRoute
  '/travels/$travelId/settings': typeof AuthenticatedTravelsTravelIdSettingsIndexRoute
  '/travels/$travelId/transactions': typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/auth': typeof ApiAuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/travels/new': typeof AuthenticatedTravelsNewRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/travels/$travelId': typeof AuthenticatedTravelsTravelIdIndexRoute
  '/travels/$travelId/settings/budgets': typeof AuthenticatedTravelsTravelIdSettingsBudgetsRoute
  '/travels/$travelId/settings/categories': typeof AuthenticatedTravelsTravelIdSettingsCategoriesRoute
  '/travels/$travelId/settings/users': typeof AuthenticatedTravelsTravelIdSettingsUsersRoute
  '/travels/$travelId/settings': typeof AuthenticatedTravelsTravelIdSettingsIndexRoute
  '/travels/$travelId/transactions': typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/auth': typeof ApiAuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/travels/$travelId': typeof AuthenticatedTravelsTravelIdRouteWithChildren
  '/_authenticated/travels/new': typeof AuthenticatedTravelsNewRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/travels/$travelId/': typeof AuthenticatedTravelsTravelIdIndexRoute
  '/_authenticated/travels/$travelId/settings/budgets': typeof AuthenticatedTravelsTravelIdSettingsBudgetsRoute
  '/_authenticated/travels/$travelId/settings/categories': typeof AuthenticatedTravelsTravelIdSettingsCategoriesRoute
  '/_authenticated/travels/$travelId/settings/users': typeof AuthenticatedTravelsTravelIdSettingsUsersRoute
  '/_authenticated/travels/$travelId/settings/': typeof AuthenticatedTravelsTravelIdSettingsIndexRoute
  '/_authenticated/travels/$travelId/transactions/': typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/api/auth'
    | '/'
    | '/travels/$travelId'
    | '/travels/new'
    | '/api/trpc/$'
    | '/travels/$travelId/'
    | '/travels/$travelId/settings/budgets'
    | '/travels/$travelId/settings/categories'
    | '/travels/$travelId/settings/users'
    | '/travels/$travelId/settings'
    | '/travels/$travelId/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/api/auth'
    | '/'
    | '/travels/new'
    | '/api/trpc/$'
    | '/travels/$travelId'
    | '/travels/$travelId/settings/budgets'
    | '/travels/$travelId/settings/categories'
    | '/travels/$travelId/settings/users'
    | '/travels/$travelId/settings'
    | '/travels/$travelId/transactions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/api/auth'
    | '/_authenticated/'
    | '/_authenticated/travels/$travelId'
    | '/_authenticated/travels/new'
    | '/api/trpc/$'
    | '/_authenticated/travels/$travelId/'
    | '/_authenticated/travels/$travelId/settings/budgets'
    | '/_authenticated/travels/$travelId/settings/categories'
    | '/_authenticated/travels/$travelId/settings/users'
    | '/_authenticated/travels/$travelId/settings/'
    | '/_authenticated/travels/$travelId/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/travels/new': {
      id: '/_authenticated/travels/new'
      path: '/travels/new'
      fullPath: '/travels/new'
      preLoaderRoute: typeof AuthenticatedTravelsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId': {
      id: '/_authenticated/travels/$travelId'
      path: '/travels/$travelId'
      fullPath: '/travels/$travelId'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/travels/$travelId/': {
      id: '/_authenticated/travels/$travelId/'
      path: '/'
      fullPath: '/travels/$travelId/'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/transactions/': {
      id: '/_authenticated/travels/$travelId/transactions/'
      path: '/transactions'
      fullPath: '/travels/$travelId/transactions'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/settings/': {
      id: '/_authenticated/travels/$travelId/settings/'
      path: '/settings'
      fullPath: '/travels/$travelId/settings'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/settings/users': {
      id: '/_authenticated/travels/$travelId/settings/users'
      path: '/settings/users'
      fullPath: '/travels/$travelId/settings/users'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/settings/categories': {
      id: '/_authenticated/travels/$travelId/settings/categories'
      path: '/settings/categories'
      fullPath: '/travels/$travelId/settings/categories'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdSettingsCategoriesRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
    '/_authenticated/travels/$travelId/settings/budgets': {
      id: '/_authenticated/travels/$travelId/settings/budgets'
      path: '/settings/budgets'
      fullPath: '/travels/$travelId/settings/budgets'
      preLoaderRoute: typeof AuthenticatedTravelsTravelIdSettingsBudgetsRouteImport
      parentRoute: typeof AuthenticatedTravelsTravelIdRoute
    }
  }
}

interface AuthenticatedTravelsTravelIdRouteChildren {
  AuthenticatedTravelsTravelIdIndexRoute: typeof AuthenticatedTravelsTravelIdIndexRoute
  AuthenticatedTravelsTravelIdSettingsBudgetsRoute: typeof AuthenticatedTravelsTravelIdSettingsBudgetsRoute
  AuthenticatedTravelsTravelIdSettingsCategoriesRoute: typeof AuthenticatedTravelsTravelIdSettingsCategoriesRoute
  AuthenticatedTravelsTravelIdSettingsUsersRoute: typeof AuthenticatedTravelsTravelIdSettingsUsersRoute
  AuthenticatedTravelsTravelIdSettingsIndexRoute: typeof AuthenticatedTravelsTravelIdSettingsIndexRoute
  AuthenticatedTravelsTravelIdTransactionsIndexRoute: typeof AuthenticatedTravelsTravelIdTransactionsIndexRoute
}

const AuthenticatedTravelsTravelIdRouteChildren: AuthenticatedTravelsTravelIdRouteChildren =
  {
    AuthenticatedTravelsTravelIdIndexRoute:
      AuthenticatedTravelsTravelIdIndexRoute,
    AuthenticatedTravelsTravelIdSettingsBudgetsRoute:
      AuthenticatedTravelsTravelIdSettingsBudgetsRoute,
    AuthenticatedTravelsTravelIdSettingsCategoriesRoute:
      AuthenticatedTravelsTravelIdSettingsCategoriesRoute,
    AuthenticatedTravelsTravelIdSettingsUsersRoute:
      AuthenticatedTravelsTravelIdSettingsUsersRoute,
    AuthenticatedTravelsTravelIdSettingsIndexRoute:
      AuthenticatedTravelsTravelIdSettingsIndexRoute,
    AuthenticatedTravelsTravelIdTransactionsIndexRoute:
      AuthenticatedTravelsTravelIdTransactionsIndexRoute,
  }

const AuthenticatedTravelsTravelIdRouteWithChildren =
  AuthenticatedTravelsTravelIdRoute._addFileChildren(
    AuthenticatedTravelsTravelIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTravelsTravelIdRoute: typeof AuthenticatedTravelsTravelIdRouteWithChildren
  AuthenticatedTravelsNewRoute: typeof AuthenticatedTravelsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTravelsTravelIdRoute:
    AuthenticatedTravelsTravelIdRouteWithChildren,
  AuthenticatedTravelsNewRoute: AuthenticatedTravelsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
