/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TravelsNewRouteImport } from './routes/travels/new'
import { Route as TravelsTravelIdIndexRouteImport } from './routes/travels/$travelId/index'
import { Route as TravelsTravelIdTransactionsNewRouteImport } from './routes/travels/$travelId/transactions/new'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api/trpc/$'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelsNewRoute = TravelsNewRouteImport.update({
  id: '/travels/new',
  path: '/travels/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelsTravelIdIndexRoute = TravelsTravelIdIndexRouteImport.update({
  id: '/travels/$travelId/',
  path: '/travels/$travelId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelsTravelIdTransactionsNewRoute =
  TravelsTravelIdTransactionsNewRouteImport.update({
    id: '/travels/$travelId/transactions/new',
    path: '/travels/$travelId/transactions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/travels/new': typeof TravelsNewRoute
  '/travels/$travelId': typeof TravelsTravelIdIndexRoute
  '/travels/$travelId/transactions/new': typeof TravelsTravelIdTransactionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/travels/new': typeof TravelsNewRoute
  '/travels/$travelId': typeof TravelsTravelIdIndexRoute
  '/travels/$travelId/transactions/new': typeof TravelsTravelIdTransactionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/travels/new': typeof TravelsNewRoute
  '/travels/$travelId/': typeof TravelsTravelIdIndexRoute
  '/travels/$travelId/transactions/new': typeof TravelsTravelIdTransactionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/travels/new'
    | '/travels/$travelId'
    | '/travels/$travelId/transactions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/travels/new'
    | '/travels/$travelId'
    | '/travels/$travelId/transactions/new'
  id:
    | '__root__'
    | '/'
    | '/travels/new'
    | '/travels/$travelId/'
    | '/travels/$travelId/transactions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TravelsNewRoute: typeof TravelsNewRoute
  TravelsTravelIdIndexRoute: typeof TravelsTravelIdIndexRoute
  TravelsTravelIdTransactionsNewRoute: typeof TravelsTravelIdTransactionsNewRoute
}
export interface FileServerRoutesByFullPath {
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/trpc/$'
  id: '__root__' | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travels/new': {
      id: '/travels/new'
      path: '/travels/new'
      fullPath: '/travels/new'
      preLoaderRoute: typeof TravelsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travels/$travelId/': {
      id: '/travels/$travelId/'
      path: '/travels/$travelId'
      fullPath: '/travels/$travelId'
      preLoaderRoute: typeof TravelsTravelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travels/$travelId/transactions/new': {
      id: '/travels/$travelId/transactions/new'
      path: '/travels/$travelId/transactions/new'
      fullPath: '/travels/$travelId/transactions/new'
      preLoaderRoute: typeof TravelsTravelIdTransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TravelsNewRoute: TravelsNewRoute,
  TravelsTravelIdIndexRoute: TravelsTravelIdIndexRoute,
  TravelsTravelIdTransactionsNewRoute: TravelsTravelIdTransactionsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
